Add linting and fix issues
I encountered this error in the happo-demo-storybook repo:

Error: Request to GET https://happo.io/api/snap-requests/3596949 failed:
500 - An error occurred for browser-chrome: page.evaluate: ReferenceError: beforeScreenshot is not defined
    at getExamples
    (http://localhost:4444/vendors~main.01c0b7244b763802541e.bundle.js:25:118246)

It turns out that we hadn't defined beforeScreenshot (or
afterScreenshot) in the <v5 code path. Linting will help us catch these
types of issues.