Subclass Error for forceHappoScreenshot
Currently forceHappoScreenshot ends up logging a message that looks like
this:

```
Error: Forced screenshot with label "foo"
  at ...
```

This is confusing, since it looks like some unhandled error. But in fact
this is just how this feature works. I think we can make this clearer by
properly subclassing the Error class. This should now look like this:

```
ForcedHappoScreenshot: Forced screenshot with label "foo"
  at ...
```