Add react to devDependencies
I'm getting errors in CI right now:

ERR! Error: Cannot find module 'react/package.json'
ERR! Require stack:
ERR! -
/home/travis/build/happo/happo-plugin-storybook/node_modules/@storybook/ui/noop.js
ERR!     at Function.Module._resolveFilename
(internal/modules/cjs/loader.js:815:15)

Adding an implicit dependency on React will hopefully help.